language: scala
scala:
  - 2.10.4
  - 2.11.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8

branches:
  only:
    - SFX-8
    - SFX-8-stable

notifications:
  email:
    - scalafx-build@googlegroups.com
