language: scala
scala:
  - 2.10.5
  - 2.11.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - stable

notifications:
  email:
    - scalafx-build@googlegroups.com
